name: Frontend CI fork

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  jest:
    runs-on: blacksmith-2vcpu-ubuntu-2204
    name: Jest test ${{ matrix.chunk }}

    strategy:
      fail-fast: false
      matrix:
        chunk: [1, 2, 3, 4, 5, 6, 7, 8]

    steps:
      - uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.x.x

      - name: Set up Node.js
        uses: useblacksmith/setup-node@v5
        with:
          node-version: 18.12.1
          cache: pnpm

      - name: Install package.json dependencies with pnpm
        run: pnpm install --frozen-lockfile

      - name: Test with Jest
        run: pnpm test:unit --shard=${{ matrix.chunk }}/8 --maxWorkers=2 --silent
