name: Frontend CI fork

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  jest-noshard:
    runs-on: blacksmith-2vcpu-ubuntu-2204
    steps:
      # we need at least one thing to run to make sure we include everything for required jobs
      - uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.x.x

      - name: Set up Node.js
        uses: useblacksmith/setup-node@v5
        with:
          node-version: 18.12.1
          cache: pnpm

      - name: Install package.json dependencies with pnpm
        run: pnpm install --frozen-lockfile

      - name: Test with Jest
        # set maxWorkers or Jest only uses 1 CPU in GitHub Actions
        run: pnpm test:unit --silent
        env:
          NODE_OPTIONS: --max-old-space-size=6144

  jest-shard:
    runs-on: blacksmith-2vcpu-ubuntu-2204
    name: Jest test ${{ matrix.chunk }}

    strategy:
      # If one test fails, still run the others
      fail-fast: false
      matrix:
        chunk: [1, 2, 3]

    steps:
      # we need at least one thing to run to make sure we include everything for required jobs
      - uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.x.x

      - name: Set up Node.js
        uses: useblacksmith/setup-node@v5
        with:
          node-version: 18.12.1
          cache: pnpm

      - name: Install package.json dependencies with pnpm
        run: pnpm install --frozen-lockfile

      - name: Test with Jest
        # set maxWorkers or Jest only uses 1 CPU in GitHub Actions
        run: pnpm test:unit --shard=${{ matrix.chunk }}/3 --silent
        env:
          NODE_OPTIONS: --max-old-space-size=6144
