name: Frontend CI - benchmark

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  jest-benchmark:
    strategy:
      matrix:
        include:
          - runner: blacksmith-2vcpu-ubuntu-2204
            maxWorkers: 2
          - runner: blacksmith-4vcpu-ubuntu-2204
            maxWorkers: 4
          - runner: blacksmith-8vcpu-ubuntu-2204
            maxWorkers: 8
          - runner: blacksmith-16vcpu-ubuntu-2204
            maxWorkers: 16

    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.x.x

      - name: Set up Node.js
        uses: useblacksmith/setup-node@v5
        with:
          node-version: 18.12.1
          cache: pnpm

      - name: Install package.json dependencies with pnpm
        run: pnpm install --frozen-lockfile

      - name: Test with Jest
        run: pnpm test:unit --silent --maxWorkers=${{ matrix.maxWorkers }}
        env:
          NODE_OPTIONS: --max-old-space-size=6144