name: Frontend CI

on:
  pull_request:
  push:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  jest-noshard:
    runs-on: blacksmith-2vcpu-ubuntu-2204
    steps:
      # we need at least one thing to run to make sure we include everything for required jobs
      - uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.x.x

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.12.1
          cache: pnpm

      - name: Install package.json dependencies with pnpm
        run: pnpm install --frozen-lockfile

      - name: Test with Jest
        # set maxWorkers or Jest only uses 1 CPU in GitHub Actions
        run: pnpm test:unit
        env:
          NODE_OPTIONS: --max-old-space-size=6144

  jest-shard:
    runs-on: blacksmith-2vcpu-ubuntu-2204
    name: Jest test (${{ matrix.segment }} - ${{ matrix.chunk }})

    strategy:
      # If one test fails, still run the others
      fail-fast: false
      matrix:
        segment: ['FOSS', 'EE']
        chunk: [1, 2, 3]

    steps:
      # we need at least one thing to run to make sure we include everything for required jobs
      - uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.x.x

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.12.1
          cache: pnpm

      - name: Install package.json dependencies with pnpm
        run: pnpm install --frozen-lockfile

      - name: Test with Jest
        # set maxWorkers or Jest only uses 1 CPU in GitHub Actions
        run: pnpm test:unit --maxWorkers=2 --shard=${{ matrix.chunk }}/3
        env:
          NODE_OPTIONS: --max-old-space-size=6144
